### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by ctfrancia** [ctfrancia/bcnchess#2]
Give the website a solid look that can be easily grown upon, for PR please include screen shots.

**Comment by akshay-nm** [comment]
Roger that

**Comment by ctfrancia** [comment]
I am going to be including screen shots of how it looks now just to give you an idea.

**Comment by akshay-nm** [comment]
Okay

**Comment by akshay-nm** [comment]
Even rough sketches would do. I am only interested in routes and components which I might have to create (initially blank). 
Content can be added later on.
Just need the desired sitemap.

**Comment by ctfrancia** [comment]
Right sorry will be adding them in an hour or so) just finishing lunch

**Comment by ctfrancia** [comment]
screen shots have been added

**Comment by mundane140** [comment]
> screen shots have been added

Where exactly 😛

**Comment by akshay-nm** [comment]
I just went through the screenshots.

# current state

## pages

- home
- about
- create tournament

## users

- people who want to create tournament
- people who want to view results of matches/ view tournaments

# Questions

## Are you assigning roles to the user? 

This could be used to provide dashboard for each type of user. You could have tournament search and tracking scores kinda features for normal users. Club related feature components could be added to the dashboard incase the user was a club manager.

## What kind of tasks are being done by the user related to tournament management?

- CRUD TOURNAMENT
- CRUD MATCHES IN AN EXISTING TOURNAMENT
- CRUD MATCHES WITHOUT TOURNAMENT (this would make the tournament field in a match document optional)

##  Are you planning on shifting to a NoSql database?

I could help with that too.

**Comment by ctfrancia** [comment]
I'm currently creating an API integration using swagger.io so that it'll be easier for you.
## Answers
Currently, there are not any 'roles' but there will be. I am going to be creating a foreign key to a "clubs" table but haven't gotten to it. I am trying to really focus on this small simple part and make sure that it is all there before trying to grow it.

Currently the users just have the opportunity to create the tournament and see the tournament. Another availability will be for them to also edit a tournament that they created(in case they put some information wrong or they are cancelling the tournament, etc.)

In terms of a NoSQL Database I haven't seen a clear use for it. The idea is also that when a sees a tournament they will have the ability to click a button that says "attend" So other people can get an idea of who will be attending it.

For the future when posting a tournament the creator/manager will also have the ability to make it private where either an invitation link is sent _or_ there is a condition (for example: Only members of my chess club can see this, Only my friends can see this, etc) but that's more in the future as this is a bit more complicated.

If there are any more questions let me know
