### ISSUE TITLE
Noob friendly setup documentation

### ISSUE THREAD

**Issue by akshay-nm** [ctfrancia/bcnchess#3]
I have no prior experience with GO. 😅
Need clear steps to setup the project to get started.

**Comment by ctfrancia** [comment]
ok. I'll get on that this morning

**Comment by ctfrancia** [comment]
I updated it. If there is anything that isn't clear let me know :)

**Comment by akshay-nm** [comment]
I'll try it out today.

**Comment by akshay-nm** [comment]
My go installation was messed up. I was able to fix it. But now I am getting an error:
`Error 1045: Access denied for user 'chess-web'@'172.22.0.1' (using password: YES)`
I am assuming this is related to the MYSQL setup. 
I have added `chess-web` and `test_bcnchess` to the user table in my MYSQL docker container. But those are @localhost. 
This IP address is different `172.22.0.1`. Maybe I need to set up some more environment variables.
I tried using `go run ./cmd/web -help` but it throws the same error.

**Comment by ctfrancia** [comment]
yes, if you look at the file `db.setup.sql` you'll see the SQL queries needed for the test user

**Comment by ctfrancia** [comment]
sql commands*

**Comment by akshay-nm** [comment]
I tried executing the file by copying the db.setup.sql file to the container, but I got a few errors. 
I'll try the whole thing one more time, I'll attach errors if I get some. 😅

**Comment by ctfrancia** [comment]
Alright, since you are creating it inside of docker you might need to create the 'chess-web'@'172.22.0.1' instead of localhost. I'm taking screen shots now.

**Comment by akshay-nm** [comment]
I am just using docker for MySQL server. 
The process just fires up a fresh instance of MySQL server on port 3306. Rest of the app just runs on my pc (ubuntu). 
Any particular environment variables you use for MySQL server?
Should the IP address of the application be same as localhost by default? Or are you using a different configuration.

**Comment by ctfrancia** [comment]
I have mysql running on my machine not through anything like docker. No necessary variables needed

**Comment by akshay-nm** [comment]
I added the 'chess-web@'172.22.0.1' as a user in the database and it seemed to work because now I am getting a different error.
`main.go:92: open ./tls/cert.pem: no such file or directory
exit status 1`

I am using `go run ./cmd/web` to run the app.

**Comment by ctfrancia** [comment]
This is because in the `./tls` is a where I have my private and public keys. You can create your own self signing certificate to run the https with the following:
1. create a `tls` folder in the root folder (where you see `cmd` folder)
2. cd into the `tls` folder
3. fun the command: `go run /usr/local/go/src/crypto/tls/generate_cert.go --rsa-bits=2048 --host=localhost`

let me know if this works or not and then I'll update the `README`

**Comment by akshay-nm** [comment]
i'll try this

**Comment by ctfrancia** [comment]
updated readme
